apiVersion: v1
kind: Service
metadata:
  name: pan-gpt-service
  namespace: slackbot
spec:
  selector:
    app: pan-gpt
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30081
  type: NodePort
