apiVersion: v1
kind: Service
metadata:
  name: panpal-service
  namespace: slackbot
spec:
  selector:
    app: panpal
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30081
  type: NodePort
