apiVersion: apps/v1
kind: Deployment
metadata:
  name: panpal-deployment
  namespace: slackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panpal
  template:
    metadata:
      labels:
        app: panpal
    spec:
      containers:
      - name: panpal-container
        image: ghcr.io/cdot65/slackbot-panpal:0.0.1
        imagePullPolicy: Always
        workingDir: /code
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
        env:
        - name: OPENAI_TOKEN
          valueFrom:
            secretKeyRef:
              name: panpal-secrets
              key: OPENAI_TOKEN
        - name: SLACKBOT_PANPAL_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: panpal-secrets
              key: SLACKBOT_PANPAL_APP_TOKEN
        - name: SLACKBOT_PANPAL_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: panpal-secrets
              key: SLACKBOT_PANPAL_BOT_TOKEN
        - name: SLACK_CHANNEL
          value: 'C040K78VC5D'
      imagePullSecrets:
      - name: dockerconfigjson-github-com
